### ISSUE TITLE
Add support for replacing dreambooth and prompt in jupyter notebook.

### ISSUE THREAD

**Issue by SHYuanBest** [camenduru/MagicTime-jupyter#2]
This is a great project, thank you for your efforts. Could you please add support for replacing dreambooth and prompt in jupyter notebook? This may be more convenient for everyone to use.

**Comment by camenduru** [comment]
thanks ❤ done 🥳

![Screenshot 2024-04-14 152633](https://github.com/camenduru/MagicTime-jupyter/assets/54370274/ede3d5b4-5e43-4e5b-a928-601e6f904f03)
