### ISSUE TITLE
Need support for ConsisID

### ISSUE THREAD

**Issue by SHYuanBest** [camenduru/MagicTime-jupyter#3]
@camenduru hi, we just develope an identity-preserving text-to-video generation model, ConsisID (base on CogVideoX-5B), which can keep human-identity consistent in the generated video. Can you help us to intergrate it into Jupyter-notebook and replicate? Thanks.

https://github.com/PKU-YuanGroup/ConsisID

**Comment by camenduru** [comment]
Thanks for the project ❤

🍇runpod: https://github.com/camenduru/consisid-tost
🍊jupyter: https://github.com/camenduru/ConsisID-jupyter
